on:
  push:
  workflow_dispatch: # only trigger when manual
name: Download Youtube Video Through Pytube

jobs:
  build:
    name: Download Video
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: SetUp Envirements
        run: pip3 install -r requirements.txt
      - name: Get Video
        run: |
          python download_video.py
      - name: Zip output
        run: |
          zip -rm --quiet -9 video.zip video/
          zip -rm --quiet -9 output.zip output/
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.head_commit.message }}
          release_name: Release - ${{ github.event.head_commit.message }}
          draft: false
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: sekwah41/upload-release-assets@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: |
            output.zip
            video.zip
          asset_name: |
            output.zip
            video.zip
          asset_content_type: application/zip